customhost = "employee.czf36x6ypxu2.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leeweichian-employee"
customregion = "us-east-1"
